services:
  nginx:
    image: nginx:1.18.0-alpine
    container_name: nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./public:/var/www/html/public
    depends_on:
      - app

  mysql:
    ports:
      - "127.0.0.1:3306:3306"
